# Generated by Django 3.0.6 on 2020-05-26 13:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Companyname', models.CharField(max_length=50)),
                ('Phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact Phone Number', max_length=128, region=None)),
                ('Address', models.CharField(max_length=100)),
                ('Industry_type', models.CharField(blank=True, max_length=50)),
                ('Skill_required', models.CharField(max_length=50)),
            ],
        ),
    ]
