# Generated by Django 3.0.6 on 2020-05-26 09:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact Phone Number', max_length=128, region=None)),
                ('Address', models.CharField(max_length=100)),
                ('Industry', models.CharField(blank=True, max_length=50)),
                ('Skill', models.CharField(max_length=50)),
                ('Aadhaar', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Aadhaar number must be entered in the format: 'XXXX XXXX XXXX'.", regex='^\\d{4}\\s\\d{4}\\s\\d{4}$')])),
                ('PAN', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Pan number must be entered in the format: 'XXXXX9999X'.( Where X ia alphabetic character and 9 is numerical digit)", regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
