# Generated by Django 3.0.6 on 2020-05-26 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='Aadhaar',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Aadhaar number must be entered in the format: 'XXXX XXXX XXXX'.", regex='^\\d{4}\\s\\d{4}\\s\\d{4}$')]),
        ),
    ]
